<div id="livreAuteur">
    <h2>Liste des livres par auteur</h2>
    <form action="auteurLivres.php" method="POST">
        <fieldset class="barreDeRecherche">
            <p>
                <label for="auteur">Recherchez votre Auteur</label>
                <input type="text" name="auteur" id="auteur" placeholder="Entrez votre recherche">
                <button type="submit">Recherche</button>
            </p>
        </fieldset>
    </form>
    <div id="listesL">
    <?php foreach($auteurLivres as $listes): ?>
        <?php
            $image = "img/". $listes['isbn'] .".jpg";
            $imageDefaut = "img/0.jpg";
        ?>
        <section>
        <figure>
            <?php if(file_exists($image)){ ?>
            <!-- ici je prend la valeur qui est présente dans ma table detailsLivres a la position zero-->
            <a href="detailsLivres.php?Id=<?= htmlspecialchars($listes['isbn']) ?>"><img src="<?= $image ?>" alt="photo du livre"></a> 
            <?php }else{ ?>
                <!-- ici je gére l'image par défauts -->
                <a href="detailsLivres.php?Id=<?= htmlspecialchars($listes['isbn']) ?>"><img src="<?= $imageDefaut ?>" alt="photo du livre"></a>
            <?php } ?>   
        </figure>
        <div class="detailsL">
            <h2><?= htmlspecialchars($listes['titre']) ?></h2>
                <p>Publiée en <?= htmlspecialchars($listes['annee']) ?></p>
                <p>Édité par: <q><?= htmlspecialchars($listes['libelle']) ?></q></p>
        </div>
        </section>
        <?php endforeach; ?>
    </div>


</div>
