<h2>Se connecter avec un compte utilisateur</h2>

<form action="connexion.php" method="POST" class="form"> 
    <fieldset>
        <legend> Informations d'autendification</legend>
        <ul>
            <li>
                <label for="mail">E-mail :</label>
                <input type="text" name="mail" id="mail" placeholder="exemple@gmail.com">
            </li>
            <li>
                <label for="mdp">Mot de passe :</label>
                <input type="password" name="mdp" id="mdp">
            </li>
        </ul>
    </fieldset>
    <button class="buttonEnregistrer" type="submit" id="creer">Connexion</button>
    <button class="buttonEffacer" type="reset" id="supprimer">Annuler</button>
</fom>
