<h2>Se connecter avec un compte utilisateur</h2>
<div class="nouveauL">
    <form action="connexion.php" method="POST" class="form"> 
        <fieldset>
            <legend> Informations d'autendification</legend>
            <ul>
                <li>
                    <label for="mail">E-mail : *</label>
                    <input type="text" name="mail" id="mail" placeholder="exemple@gmail.com" autofocus required>
                </li>
                <li>
                    <label for="mdp">Mot de passe : *</label>
                    <input type="password" name="mdp" id="mdp" placeholder="**********" required>
                </li>
            </ul>
            <button class="buttonSubmit" type="submit" id="creer">Connexion</button>
            <a class="buttonEffacer" href="listesLivres.php">Annuler</a>
        </fieldset>
    </fom>
</div>