<div id="detailsLivres">
   <?php
            $image = "img/". $detailsLivres[0]['isbn'] .".jpg";
            $imageDefaut = "img/0.jpg";?>
    <section>
        <figure>
        <?php if(file_exists($image)){ ?>
        <!-- ici je prend la valeur qui est présente dans ma table detailsLivres a la position zero-->
            <a href="detailsLivres.php?Id=<?= htmlspecialchars($detailsLivres[0]['isbn']) ?>"><img src="<?= $image ?>" alt="photo du livre"></a> 
        <?php }else{ ?>
        <!-- ici je gére l'image par défauts -->
            <a href="detailsLivres.php?Id=<?= htmlspecialchars($detailsLivres[0]['isbn']) ?>"><img src="<?= $imageDefaut ?>" alt="photo du livre"></a>
        <?php } ?>
        </figure>
        <div class="detailsL">
            <h2><?= htmlspecialchars($detailsLivres[0]['titre']) ?></h2>
                <p>Publié en <?= htmlspecialchars($detailsLivres[0]['annee']) ?></p>
                <p>Édité par : <q><?= htmlspecialchars($detailsLivres[0]['nomEditeur']) ?></q></p>
            <!-- ici je boucle dans le tableau pour afficher le nom et le role des differentes personnes qui ont travailler sur le livre-->
                <?php foreach($detailsLivres as $details): ?>
                    <p>Rôle de <?= htmlspecialchars($details['nom']) ?> <?= htmlspecialchars($details['prenom']) ?> : <?= htmlspecialchars($details['role']) ?></p>
                <?php endforeach; ?>
                <p>Disponible en : <?= htmlspecialchars($detailsLivres[0]['langue']) ?></p>
                <?php if(!($detailsLivres[0]['nbpages'] == NULL)){ ?>
                    <p>Nombres de pages : <?= htmlspecialchars($detailsLivres[0]['nbpages']) ?></p>
                <?php } ?>
                <!-- ajout d'un bouton si l'utilisateur est connecté -->
                <?php if(isset($_SESSION['connexion'])){ ?>
                <a class="boutonResa" href="reservation_panier.php?Id=<?= htmlspecialchars($detailsLivres[0]['isbn']) ?>">Réserver <i class="fas fa-arrow-circle-right"></i></a>
                <?php } ?>
        </div>
    </section>
</div>

