<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>bibliotheque</title>
    <link rel="stylesheet" href="css/styles.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Dancing+Script|Pacifico&display=swap">
</head>
<body>
    <header>
        <h1>Bibliotheque de livre</h1>
        <div class="flexHeader">
            <figure>
                <img src="img/logo-bibliothèque.png" alt="logo">
            </figure>
            <nav>
                <ul>
                    <li><a href="listesLivres.php">Tous les Livres</a></li>
                    <li><a href="#">Par auteur</a></li>
                    <li><a href="#">Par année</a></li>
                    <li><a href="nouveauLivres.php">Nouveau livre</a></li>
                </ul>
            </nav>
    </div>
    </header>
        <main>
            <?php include $template.'.phtml'; ?>
        </main>
    <footer>
        <nav>
            <ul>
                <li><a href="listesLivres.php">Tous les Livres</a></li>
                <li><a href="#">Par auteur</a></li>
                <li><a href="#">Par année</a></li>
                <li><a href="nouveauLivres.php">Nouveau livre</a></li>
            </ul>
        </nav>
    </footer>
</body>
</html>