<div class="barRecherche">
    <form action="auteurLivres.php" method="POST">
            <fieldset class="barreDeRecherche">
                <p class="flexBR">
                    <label for="auteur">Recherchez votre Auteur</label>
                    <input type="text" name="auteur" id="auteur" placeholder="Entrez votre recherche">
                    <button type="submit">Recherche</button>
                </p>
            </fieldset>
    </form>
</div>
<div class="bg_image_accueil">
    <div id="accueil">
        <h2>Bienvenue sur notre site</h2>
            <p>Bibliothèque vous proposent une <em>large gamme de livres</em>, des auteurs très connus et vous offres la possibilité de les rechercher par <em>auteur</em> ou par <em>année...</em></p>
           <figure>
                <img src="img/club_lecture.jpg" alt="club de Lecture">
           </figure>
            
    </div>
</div>
