<?php session_start(); ?>
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="css/styles.css">
    <link rel="shortcut icon" type="image/x-icon" href="img/logo-bibliothèque.png" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Dancing+Script|Pacifico&display=swap">
    <script src="https://kit.fontawesome.com/f2574f15cd.js" crossorigin="anonymous"></script>
    <title>bibliotheque</title>
    <script src="js/javascript.js"></script>
</head>
<body>
    <header>
        <a href="listesLivres.php"><h1>Bibliotheque de livre</h1></a>
        <?php if(isset($_SESSION['connexion']) && $_SESSION['admin'] == 1 ){ ?>
        <h2 style="color: #E26B01">Bienvenue <?= $_SESSION['prenom'] ?></h2>
        <?php } ?>
        <?php if(isset($_SESSION['connexion']) && $_SESSION['admin'] == 0 ){ ?>
        <h2>Bienvenue <?= $_SESSION['prenom'] ?></h2>
        <?php } ?>
        <div class="flexHeader">
            <figure>
                <a href="index.php"><img src="img/logo-bibliothèque.png" alt="logo"></a>
            </figure>
            <nav>
                <ul>
                <?php if(isset($_SESSION['connexion']) && $_SESSION['admin'] == 1){ ?> 
                    <li><a href="index.php"><i class="fas fa-home"></i></a></li> 
                    <li><a href="listesLivres.php">Tous les Livres</a></li>
                    <li><a href="admin.php">Admin</a></li>
                    <li><a href="deconnexion.php">Déconnexion</a></li>
                <?php }else if(isset($_SESSION['connexion'])&& $_SESSION['admin'] == 0){ ?> 
                    <li><a href="index.php"><i class="fas fa-home"></i></a></li> 
                    <li><a href="listesLivres.php">Tous les Livres</a></li>
                    <li><a href="anneeLivres.php">Par année</a></li>
                    <li><a href="deconnexion.php">deconnexion</a></li>
                <?php }else{ ?>
                    <li><a href="index.php"><i class="fas fa-home"></i></a></li>
                    <li><a href="listesLivres.php">Tous les Livres</a></li>
                    <li><a href="anneeLivres.php">Par Année</a></li>
                    <li><a href="inscription.php">Inscription</a></li>
                    <li><a href="connexion.php">Connexion</a></li>
               <?php } ?>
                </ul>
            </nav>
    </div>
    </header>
        <main>
            <?php include $template.'.phtml'; ?>
        </main>
    <footer>
        <nav>
            <ul>
            <?php if(isset($_SESSION['connexion']) && $_SESSION['admin'] == 1){ ?>
                    <li><a href="listesLivres.php">Tous les Livres</a></li>
                    <li><a href="admin.php">Admin</a></li>
                    <li><a href="deconnexion.php">Déconnexion</a></li>
                <?php }else if(isset($_SESSION['connexion'])&& $_SESSION['admin'] == 0){ ?>  
                    <li><a href="listesLivres.php">Tous les Livres</a></li>
                    <li><a href="anneeLivres.php">Par année</a></li>
                    <li><a href="deconnexion.php">deconnexion</a></li>
                <?php }else{ ?>
                    <li><a href="listesLivres.php">Tous les Livres</a></li>
                    <li><a href="anneeLivres.php">Par Année</a></li>
                    <li><a href="inscription.php">Inscription</a></li>
                    <li><a href="connexion.php">Connexion</a></li>
               <?php } ?>
            </ul>
        </nav>
        <div class="footer">
        <p>Fait par l'entreprise yc-développeur France</p>
        <a href="#"><i class="fab fa-facebook-square fa-2x facebook"></i></a>
        <a href="#"><i class="fab fa-instagram-square fa-2x instagram"></i></a>
        <a href="#"><i class="fab fa-twitter-square fa-2x twitter"></i></a>
        <p>© 2020 Yann & Clément yc-développeur@gmail.com</p>
        </div>
    </footer>
</body>
</html>