<?php session_start(); ?>
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>bibliotheque</title>
    <link rel="stylesheet" href="css/styles.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Dancing+Script|Pacifico&display=swap">
    <script src="js/javascript.js"></script>
</head>
<body>
    <header>
        <a href="listesLivres.php"><h1>Bibliotheque de livre</h1></a>
        <?php if($_SESSION['admin'] == 1 ){ ?>
        <h2>Bienvenue <?= $_SESSION['prenom'] ?></h2>
        <?php } ?>
        <div class="flexHeader">
            <figure>
                <a href="index.php"><img src="img/logo-bibliothèque.png" alt="logo"></a>
            </figure>
            <nav>
                <ul>
                <?php if($_SESSION['admin'] == 1){ ?>
                    <li><a href="listesLivres.php">Tous les Livres</a></li>
                    <li><a href="admin.php">Admin</a></li>
                    <li><a href="deconnexion.php">Déconnexion</a></li>
                <?php }else if(isset($_SESSION['connexion'])){ ?>   
                    <li><a href="listesLivres.php">Tous les Livres</a></li>
                    <li><a href="auteurLivres.php">Par auteur</a></li>
                    <li><a href="anneeLivres.php">Par année</a></li>
                    <li><a href="deconnexion.php">deconnexion</a></li>
                <?php }else{ ?>
                    <li><a href="listesLivres.php">Tous les Livres</a></li>
                    <li><a href="auteurLivres.php">Par Auteur</a></li>
                    <li><a href="anneeLivres.php">Par Année</a></li>
                    <li><a href="inscription.php">Inscription</a></li>
                    <li><a href="connexion.php">Connexion</a></li>
               <?php } ?>
                </ul>
            </nav>
    </div>
    </header>
        <main>
            <?php include $template.'.phtml'; ?>
        </main>
    <footer>
        <nav>
            <ul>
                <?php if($_SESSION['admin'] == 1){ ?>
                    <li><a href="listesLivres.php">Tous les Livres</a></li>
                    <li><a href="admin.php">Admin</a></li>
                    <li><a href="deconnexion.php">Déconnexion</a></li>
                <?php }else if(isset($_SESSION['connexion'])){ ?>   
                    <li><a href="listesLivres.php">Tous les Livres</a></li>
                    <li><a href="auteurLivres.php">Par auteur</a></li>
                    <li><a href="anneeLivres.php">Par année</a></li>
                    <li><a href="deconnexion.php">deconnexion</a></li>
                <?php }else{ ?>
                    <li><a href="listesLivres.php">Tous les Livres</a></li>
                    <li><a href="auteurLivres.php">Par Auteur</a></li>
                    <li><a href="anneeLivres.php">Par Année</a></li>
                    <li><a href="inscription.php">Inscription</a></li>
                    <li><a href="connexion.php">Connexion</a></li>
               <?php } ?>
            </ul>
        </nav>
        <div class="footer">
        <p>Fait par l'entreprise yc-développeur France</p>
        <p>© 2020 Yann & Clément yc-développeur@gmail.com</p>
        </div>
    </footer>
</body>
</html>