<div class="barRecherche">
    <form action="auteurLivres.php" method="POST">
            <fieldset class="barreDeRecherche">
                <p class="flexBR">
                    <label for="auteur">Recherchez votre Auteur</label>
                    <input type="text" name="auteur" id="auteur" placeholder="Entrez votre recherche">
                    <button type="submit">Recherche</button>
                </p>
            </fieldset>
    </form>
</div>
<div id="listesL">
    <div class="listeAuteur">
        <!-- liste des auteurs -->
        <table class="table">
                <caption>Liste des auteurs</caption>
                <thead class="admin_thead">
                    <th>Nom</th>
                    <th>Prénom</th>
                </thead>
                <tbody>
                    <?php foreach ($listes_Auteur as $list): ?>
                    <tr>
                        <td><?= Htmlspecialchars($list['nom']) ?></td>
                        <td><?= Htmlspecialchars($list['prenom']) ?></td>
                    </tr>
                    <?php endforeach ?>
                </tbody>
        </table>
    </div>
    
    <?php foreach($listes_Livres as $listes): 
            $image = "img/". $listes['isbn'] .".jpg";
            $imageDefaut = "img/0.jpg";?>
    <section>
        <div>
        <figure>
        <?php if(file_exists($image)){ ?>
            <a href="detailsLivres.php?Id=<?= htmlspecialchars($listes['isbn']) ?>"><img src="<?= $image ?>" alt="photo du livre"></a> 
        <?php }else{ ?>
            <a href="detailsLivres.php?Id=<?= htmlspecialchars($listes['isbn']) ?>"><img src="<?= $imageDefaut ?>" alt="photo du livre"></a>
        <?php } ?>   
        </figure>
        </div>
        <div class="detailsL">
            <h2><?= htmlspecialchars($listes['titre']) ?></h2>
                <p>Publié en <?= htmlspecialchars($listes['annee']) ?></p>
                <p>Édité par <q><?= htmlspecialchars($listes['nomEditeur']) ?></q></p>
                <p>Genre : <?= htmlspecialchars($listes['nomGenre']) ?></p>
        </div>
    </section>
    <?php endforeach; ?>
</div>