<h2><i class="fas fa-book-open fa-2X"></i> Ajoutez un nouveau livre</h2>
<div id="nouveauL">
    <form name="formNewL" action="nouveauLivres.php" onsubmit="return validateForm()" method="POST">
        <fieldset>
            <legend>Nouveau Livre</legend>
            <ul>
                <li>
                    <label for="isbn">isbn :</label>
                    <input type="text" id="isbn" name="isbn" onfocus="this.value=''"><span class="erreur"></span>
                </li>
                <li>
                    <label for="titre">Titre :</label>
                    <input type="text" id="titre" name="titre" onfocus="this.value=''"><span class="erreur"></span>
                </li>
                <li>
                    <label for="editeur">Editeur :</label>
                    <select name="editeur" id="editeur" for="editeur">
                    <?php foreach($resultEditeur as $editeurs): ?>
                        <option value="<?= Htmlspecialchars($editeurs['id']) ?>"><?= Htmlspecialchars($editeurs['libelle']) ?></option>
                    <?php endforeach ?>
                    </select>
                </li>
                <li>
                    <label for="annee">Année :</label>
                    <input type="number" id="annee" name="annee" onfocus="this.value=''"><span class="erreur"></span>
                </li>
                <li>
                    <label for="genre">Genre :</label>
                    <select name="genre" id="genre" for="genre">
                    <?php foreach($resultGenre as $genres): ?>
                        <option value="<?= Htmlspecialchars($genres['id']) ?>"><?= Htmlspecialchars($genres['libelle']) ?></option>
                    <?php endforeach ?>
                    </select>
                </li>                   
                <li>
                    <label for="langue">Langue :</label>
                    <select name="langue" id="langue" for="langue">
                    <?php foreach($resultLangue as $langues): ?>
                        <option value="<?= Htmlspecialchars($langues['id']) ?>"><?= Htmlspecialchars($langues['libelle']) ?></option>
                    <?php endforeach ?>
                    </select>
                </li>
                <li>
                    <label for="nbpages">Nombre de pages :</label>
                    <input type="text" id="nbpages" name="nbpages" onfocus="this.value=''" value="4"><span id="erreur"></span>
                </li>
                <li class="boutton">
                    <button class="buttonSubmit" type="submit">Enregistrer</button>
                    <button class="reset" type="reset">reset</button>
                    <a class="buttonEffacer" href="listesLivres.php">Annuler</a>
                </li>
            </ul>
        </fieldset>
    </form>
</div>