
    <div class="centerForm">
        <h2><i class="fas fa-edit fa-2X"></i> Genres</h2>
        <div class="nouveauL">
            <table id="genre">
                <tr>
                    <th>Genres</th>
                </tr>
                <?php foreach($genres as $genre): ?>
                <tr>
                    <td><?= $genre['libelle'] ?></td>
                </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
    <div class="centerForm">
        <h2><i class="fas fa-edit fa-2X"></i> Ajoutez un nouveau Genre</h2>
            <div class="nouveauL">
                <form action="nouveauGenre.php" method="POST">
                    <fieldset>
                        <legend>Nouveau Genre</legend>
                        <ul>
                            <li>
                                <label for="genre">Genre :</label>
                                <input type="text" id="genre" name="genre">
                            </li>
                            <li class="boutton">
                                <button class="buttonSubmit" type="submit">Enregistrer</button>
                                <a class="buttonEffacer" href="admin.php">Annuler</a>
                            </li>
                        </ul>
                    </fieldset>
                </form>
            </div>
    </div> 

    