<div class="centerForm">
    <h2><i class="fas fa-language"></i> Langues</h2>
    <div class="nouveauL">
        <?php foreach($langues as $langue): ?>
        <p>Langue: <?= $langue['libelle'] ?></p>
        <?php endforeach; ?>
    </div>
    <h2><i class="fas fa-language"></i> Ajoutez une nouvelle Langue</h2>
    <div class="nouveauL">
        <form action="nouvelleLangue.php" method="POST">
            <fieldset>
                <legend>Nouvelle Langue</legend>
                <ul>
                    <li>
                        <label for="langue">Langue :</label>
                        <input type="text" id="langue" name="langue">
                    </li>
                    <li class="boutton">
                        <button class="buttonSubmit" type="submit">Enregistrer</button>
                        <a class="buttonEffacer" href="admin.php">Annuler</a>
                    </li>
                </ul>
            </fieldset>
        </form>
    </div>
</div>