<div class="centerForm">
    <h2><i class="fas fa-pen-nib"></i> Auteurs</h2>
    <div class="nouveauL">
        <?php foreach($personnes as $personne): ?>
        <p>Auteurs: <?= $personne['nom'] ?> <?= $personne['prenom'] ?></p>
        <?php endforeach; ?>
    </div>
    <h2><i class="fas fa-pen-nib"></i> Ajoutez une nouvelle personne</h2>
    <div class="nouveauL">
        <form action="nouvellePersonne.php" method="POST">
            <fieldset>
                <legend>Nouvelle Personne</legend>
                <ul>
                    <li>
                        <label for="nom">Nom :</label>
                        <input type="text" id="nom" name="nom">
                    </li>
                    <li>
                        <label for="prenom">Prenom :</label>
                        <input type="text" id="prenom" name="prenom">
                    </li>
                    <li class="boutton">
                        <button class="buttonSubmit" type="submit">Ajouter</button>
                        <a class="buttonEffacer" href="admin.php">Annuler</a>
                    </li>
                </ul>
            </fieldset>
        </form>
    </div>
<div>